<?php

/**
 * config.inc of Nesys_at_Home.
 * User: Al_Bundy@breakingcades.info
 * Date: 8/24/2017
 * Time: 10:14 AM
 */

define('MYSQL_USERNAME', 'stats');
define('MYSQL_PASSWORD', 'breakingMysql');
define('MYSQL_HOSTNAME', 'localhost');
define('MYSQL_PORT', 3306);
define('MYSQL_SERVICE_NAME', 'XE');
define('RANKING_2110_DATABASE', '2110_ranking');
define('RANKING_3032_CARD', '3032_card');
define('RANKING_3032_DATABASE', '3032_ranking');
define('RANKING_2110_CARD', '2110_card');
define('CERT_DATABASE', 'cert');
define('NESYS_DATABASE', 'nesys');